<script lang="ts">
	import { page } from '$app/state';
	import ConfidenceMeter from '$lib/components/ConfidenceMeter.svelte';
	import Icon from '$lib/components/Icon.svelte';
	import InfoTip from '$lib/components/InfoTip.svelte';
	import StatusBadge from '$lib/components/StatusBadge.svelte';
	import { fmtDateTime, WP_TYPE } from '$lib/format';

	let { data, children } = $props();

	const base = $derived(`/work-products/${data.wp.id}`);
	// The workspace tab is active on the child route; Summary is the index route.
	const onWorkspace = $derived(page.url.pathname.startsWith(`${base}/workspace`));

	// Confidence is the supervision signal — the mean across the claims actually
	// studied, not the work product's seeded self-reported prior. Null until the
	// first claim is run, so the header never feigns a verdict it doesn't have.
	const assessed = $derived(data.assessed);
</script>

<a class="back" href="/matters/{data.wp.matterId}"
	><Icon name="arrow-right" size={14} class="flip" /> Back to {data.wp.matterName}</a
>

<header class="hdr">
	<div class="eyebrow itaily-eyebrow">
		<InfoTip align="left">
			{#snippet label()}
				<Icon name={WP_TYPE[data.wp.type].icon} size={12} />
				<span>{WP_TYPE[data.wp.type].label}</span>
			{/snippet}
			<strong>{WP_TYPE[data.wp.type].label}</strong>
			<p>{WP_TYPE[data.wp.type].desc}</p>
		</InfoTip>
		<span>·</span>
		<a class="matter-link" href="/matters/{data.wp.matterId}">{data.wp.matterName} · {data.wp.matterRef}</a>
	</div>
	<h1>{data.wp.title}</h1>
	<p class="summary">{data.wp.summary}</p>
	<div class="meta">
		<StatusBadge status={data.wp.status} />
		{#if assessed.mean !== null}
			<span class="conf">
				<ConfidenceMeter value={assessed.mean} />
				<span class="conf-src" title="Mean confidence across the claims analyzed so far">
					{assessed.analyzed}/{assessed.total} claims assessed
				</span>
			</span>
		{:else}
			<span class="m unassessed" title="Confidence is derived per claim — run the claims in the work area to assess this document">
				<Icon name="circle-alert" size={13} /> Not yet assessed · {assessed.total} claim{assessed.total === 1 ? '' : 's'}
			</span>
		{/if}
		<span class="m"><Icon name="sparkles" size={13} /> Generated by {data.wp.agentName}</span>
		<span class="m mono">{data.wp.model}</span>
		<span class="m mono"><Icon name="clock" size={12} /> {fmtDateTime(data.wp.createdAt)}</span>
	</div>
</header>

<nav class="tabs">
	<a class="tab" class:active={!onWorkspace} href={base} data-sveltekit-noscroll>
		<Icon name="file-text" size={15} /> Summary
	</a>
	<a class="tab" class:active={onWorkspace} href={`${base}/workspace`} data-sveltekit-noscroll>
		<Icon name="git-branch" size={15} /> Work area
	</a>
</nav>

{@render children()}

<style>
	.back {
		display: inline-flex;
		align-items: center;
		gap: 6px;
		font-size: var(--text-sm);
		color: var(--text-secondary);
		text-decoration: none;
		margin-bottom: var(--space-4);
	}
	.back:hover {
		color: var(--text-link);
	}
	.back :global(.flip) {
		transform: rotate(180deg);
	}

	.hdr {
		margin-bottom: var(--space-4);
	}
	.eyebrow {
		display: inline-flex;
		align-items: center;
		gap: 6px;
		margin-bottom: 8px;
	}
	.matter-link {
		color: inherit;
		text-decoration: none;
	}
	.matter-link:hover {
		color: var(--text-link);
		text-decoration: underline;
	}
	.hdr h1 {
		font-size: var(--text-xl);
		margin: 0 0 8px;
		line-height: var(--leading-snug);
	}
	.summary {
		margin: 0 0 14px;
		max-width: 80ch;
		font-size: var(--text-md);
		color: var(--text-secondary);
		line-height: var(--leading-normal);
	}
	.meta {
		display: flex;
		align-items: center;
		gap: 16px;
		flex-wrap: wrap;
	}
	.meta .m {
		display: inline-flex;
		align-items: center;
		gap: 5px;
		font-size: var(--text-xs);
		color: var(--text-tertiary);
	}
	.meta .mono {
		font-family: var(--font-mono);
	}
	.meta .conf {
		display: inline-flex;
		align-items: center;
		gap: 8px;
	}
	.meta .conf-src {
		font-size: 10px;
		font-family: var(--font-mono);
		color: var(--text-tertiary);
		white-space: nowrap;
	}
	.meta .unassessed {
		color: var(--text-secondary);
	}

	.tabs {
		display: flex;
		gap: var(--space-1);
		margin-bottom: var(--space-5);
		border-bottom: 1.5px solid var(--border-default);
	}
	.tab {
		display: inline-flex;
		align-items: center;
		gap: 7px;
		padding: 10px 14px;
		margin-bottom: -1.5px;
		font-family: var(--font-display);
		font-weight: var(--weight-medium);
		font-size: var(--text-sm);
		color: var(--text-secondary);
		text-decoration: none;
		border-bottom: 2.5px solid transparent;
		transition: color var(--duration-fast) var(--ease-out);
	}
	.tab:hover {
		color: var(--text-primary);
	}
	.tab.active {
		color: var(--color-accent-active);
		border-bottom-color: var(--color-accent);
	}
</style>
